/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Modelo de Conta bancária no sistema bancário brasileiro
 **/
@ApiModel(description = "Modelo de Conta bancária no sistema bancário brasileiro")
public class ContaBancaria {
  
  @SerializedName("banco")
  private String banco = null;
  @SerializedName("agencia")
  private String agencia = null;
  @SerializedName("conta")
  private String conta = null;
  @SerializedName("digito")
  private String digito = null;

  /**
   * Banco da conta, string com o numero do banco
   **/
  @ApiModelProperty(value = "Banco da conta, string com o numero do banco")
  public String getBanco() {
    return banco;
  }
  public void setBanco(String banco) {
    this.banco = banco;
  }

  /**
   * Agencia bancaria da conta corrente
   **/
  @ApiModelProperty(value = "Agencia bancaria da conta corrente")
  public String getAgencia() {
    return agencia;
  }
  public void setAgencia(String agencia) {
    this.agencia = agencia;
  }

  /**
   * numero da conta corrente sem o dígito verificador
   **/
  @ApiModelProperty(value = "numero da conta corrente sem o dígito verificador")
  public String getConta() {
    return conta;
  }
  public void setConta(String conta) {
    this.conta = conta;
  }

  /**
   * digito verificador da conta corrente
   **/
  @ApiModelProperty(value = "digito verificador da conta corrente")
  public String getDigito() {
    return digito;
  }
  public void setDigito(String digito) {
    this.digito = digito;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContaBancaria contaBancaria = (ContaBancaria) o;
    return (this.banco == null ? contaBancaria.banco == null : this.banco.equals(contaBancaria.banco)) &&
        (this.agencia == null ? contaBancaria.agencia == null : this.agencia.equals(contaBancaria.agencia)) &&
        (this.conta == null ? contaBancaria.conta == null : this.conta.equals(contaBancaria.conta)) &&
        (this.digito == null ? contaBancaria.digito == null : this.digito.equals(contaBancaria.digito));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.banco == null ? 0: this.banco.hashCode());
    result = 31 * result + (this.agencia == null ? 0: this.agencia.hashCode());
    result = 31 * result + (this.conta == null ? 0: this.conta.hashCode());
    result = 31 * result + (this.digito == null ? 0: this.digito.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContaBancaria {\n");
    
    sb.append("  banco: ").append(banco).append("\n");
    sb.append("  agencia: ").append(agencia).append("\n");
    sb.append("  conta: ").append(conta).append("\n");
    sb.append("  digito: ").append(digito).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
