/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Dados profissionais do usuário
 **/
@ApiModel(description = "Dados profissionais do usuário")
public class DadosProfissionais {
  
  @SerializedName("profissao")
  private String profissao = null;
  @SerializedName("empresa")
  private String empresa = null;

  /**
   * Profissão de acordo com a tabela de ocupação profissional
   **/
  @ApiModelProperty(value = "Profissão de acordo com a tabela de ocupação profissional")
  public String getProfissao() {
    return profissao;
  }
  public void setProfissao(String profissao) {
    this.profissao = profissao;
  }

  /**
   * Nome da empresa em que trabalha o usuário
   **/
  @ApiModelProperty(value = "Nome da empresa em que trabalha o usuário")
  public String getEmpresa() {
    return empresa;
  }
  public void setEmpresa(String empresa) {
    this.empresa = empresa;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosProfissionais dadosProfissionais = (DadosProfissionais) o;
    return (this.profissao == null ? dadosProfissionais.profissao == null : this.profissao.equals(dadosProfissionais.profissao)) &&
        (this.empresa == null ? dadosProfissionais.empresa == null : this.empresa.equals(dadosProfissionais.empresa));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.profissao == null ? 0: this.profissao.hashCode());
    result = 31 * result + (this.empresa == null ? 0: this.empresa.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosProfissionais {\n");
    
    sb.append("  profissao: ").append(profissao).append("\n");
    sb.append("  empresa: ").append(empresa).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
