/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Informação sobre o Patrimônio do usuário
 **/
@ApiModel(description = "Informação sobre o Patrimônio do usuário")
public class DadosPatrimonial {
  
  public enum ValorDePatrimonioEnum {
     0,  1,  2,  3,  4,  5,  6, 
  };
  @SerializedName("valorDePatrimonio")
  private ValorDePatrimonioEnum valorDePatrimonio = null;
  @SerializedName("valorDeInvestimento")
  private BigDecimal valorDeInvestimento = null;
  public enum RendimentoMensalEnum {
     0,  1,  2,  3,  4,  5,  6, 
  };
  @SerializedName("rendimentoMensal")
  private RendimentoMensalEnum rendimentoMensal = null;
  @SerializedName("outrosBensValor")
  private BigDecimal outrosBensValor = null;

  /**
   * Código do valor total do patrimonio. Cada número representa um intervalo de valor em reais (R$). Por exemplo, 0: 'Nenhum', 1: 'Até R$50.000,00', 2: 'De R$50.000,01 à R$100.000,00', 3: 'De R$100.000,01 à R$200.000,00', 4: 'De R$200.000,01 à R$300.000,00', 5: 'De R$300.000,01 à R$1.000.000,00', 6: 'Acima de R$1.000.000,00'
   **/
  @ApiModelProperty(value = "Código do valor total do patrimonio. Cada número representa um intervalo de valor em reais (R$). Por exemplo, 0: 'Nenhum', 1: 'Até R$50.000,00', 2: 'De R$50.000,01 à R$100.000,00', 3: 'De R$100.000,01 à R$200.000,00', 4: 'De R$200.000,01 à R$300.000,00', 5: 'De R$300.000,01 à R$1.000.000,00', 6: 'Acima de R$1.000.000,00'")
  public ValorDePatrimonioEnum getValorDePatrimonio() {
    return valorDePatrimonio;
  }
  public void setValorDePatrimonio(ValorDePatrimonioEnum valorDePatrimonio) {
    this.valorDePatrimonio = valorDePatrimonio;
  }

  /**
   * Valor em R$ (inteiro) disponível para investimento
   **/
  @ApiModelProperty(value = "Valor em R$ (inteiro) disponível para investimento")
  public BigDecimal getValorDeInvestimento() {
    return valorDeInvestimento;
  }
  public void setValorDeInvestimento(BigDecimal valorDeInvestimento) {
    this.valorDeInvestimento = valorDeInvestimento;
  }

  /**
   * Código do valor que representa a renta bruta mensal. Cada número representa um intervalo de valor em reais (R$). Por exemplo, 0: 'Nenhum', 1: 'Até R$5.000,00', 2: 'De R$5.000,01 à R$10.000,00', 3: 'De R$10.000,01 à R$20.000,00', 4: 'De R$20.000,01 à R$30.000,00', 5: 'De R$30.000,01 à R$100.000,00', 6: 'Acima de R$100.000,00'
   **/
  @ApiModelProperty(value = "Código do valor que representa a renta bruta mensal. Cada número representa um intervalo de valor em reais (R$). Por exemplo, 0: 'Nenhum', 1: 'Até R$5.000,00', 2: 'De R$5.000,01 à R$10.000,00', 3: 'De R$10.000,01 à R$20.000,00', 4: 'De R$20.000,01 à R$30.000,00', 5: 'De R$30.000,01 à R$100.000,00', 6: 'Acima de R$100.000,00'")
  public RendimentoMensalEnum getRendimentoMensal() {
    return rendimentoMensal;
  }
  public void setRendimentoMensal(RendimentoMensalEnum rendimentoMensal) {
    this.rendimentoMensal = rendimentoMensal;
  }

  /**
   * Valor em R$ de outros bens do usuário
   **/
  @ApiModelProperty(value = "Valor em R$ de outros bens do usuário")
  public BigDecimal getOutrosBensValor() {
    return outrosBensValor;
  }
  public void setOutrosBensValor(BigDecimal outrosBensValor) {
    this.outrosBensValor = outrosBensValor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosPatrimonial dadosPatrimonial = (DadosPatrimonial) o;
    return (this.valorDePatrimonio == null ? dadosPatrimonial.valorDePatrimonio == null : this.valorDePatrimonio.equals(dadosPatrimonial.valorDePatrimonio)) &&
        (this.valorDeInvestimento == null ? dadosPatrimonial.valorDeInvestimento == null : this.valorDeInvestimento.equals(dadosPatrimonial.valorDeInvestimento)) &&
        (this.rendimentoMensal == null ? dadosPatrimonial.rendimentoMensal == null : this.rendimentoMensal.equals(dadosPatrimonial.rendimentoMensal)) &&
        (this.outrosBensValor == null ? dadosPatrimonial.outrosBensValor == null : this.outrosBensValor.equals(dadosPatrimonial.outrosBensValor));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.valorDePatrimonio == null ? 0: this.valorDePatrimonio.hashCode());
    result = 31 * result + (this.valorDeInvestimento == null ? 0: this.valorDeInvestimento.hashCode());
    result = 31 * result + (this.rendimentoMensal == null ? 0: this.rendimentoMensal.hashCode());
    result = 31 * result + (this.outrosBensValor == null ? 0: this.outrosBensValor.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosPatrimonial {\n");
    
    sb.append("  valorDePatrimonio: ").append(valorDePatrimonio).append("\n");
    sb.append("  valorDeInvestimento: ").append(valorDeInvestimento).append("\n");
    sb.append("  rendimentoMensal: ").append(rendimentoMensal).append("\n");
    sb.append("  outrosBensValor: ").append(outrosBensValor).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
