/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Documentação do Usuário
 **/
@ApiModel(description = "Documentação do Usuário")
public class Documento {
  
  public enum TipoDocumentoEnum {
     Carteira de Habilitação - CNH,  Passaporte,  Cart. Ident. Estrangeiro - RNE,  Cart. Identidade Profissional,  Carteira de Identidade / RG, 
  };
  @SerializedName("tipoDocumento")
  private TipoDocumentoEnum tipoDocumento = null;
  @SerializedName("numeroDocumento")
  private String numeroDocumento = null;
  @SerializedName("orgaoExpedidor")
  private String orgaoExpedidor = null;
  @SerializedName("ufEmissao")
  private String ufEmissao = null;
  @SerializedName("dataEmissao")
  private Date dataEmissao = null;
  @SerializedName("dataValidade")
  private Date dataValidade = null;
  @SerializedName("codigoSegurancaCNH")
  private String codigoSegurancaCNH = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public TipoDocumentoEnum getTipoDocumento() {
    return tipoDocumento;
  }
  public void setTipoDocumento(TipoDocumentoEnum tipoDocumento) {
    this.tipoDocumento = tipoDocumento;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNumeroDocumento() {
    return numeroDocumento;
  }
  public void setNumeroDocumento(String numeroDocumento) {
    this.numeroDocumento = numeroDocumento;
  }

  /**
   * Orgão expedidor de acordo com o tipo de documento
   **/
  @ApiModelProperty(value = "Orgão expedidor de acordo com o tipo de documento")
  public String getOrgaoExpedidor() {
    return orgaoExpedidor;
  }
  public void setOrgaoExpedidor(String orgaoExpedidor) {
    this.orgaoExpedidor = orgaoExpedidor;
  }

  /**
   * Unidade da Federação onde foi emitido o documeto
   **/
  @ApiModelProperty(value = "Unidade da Federação onde foi emitido o documeto")
  public String getUfEmissao() {
    return ufEmissao;
  }
  public void setUfEmissao(String ufEmissao) {
    this.ufEmissao = ufEmissao;
  }

  /**
   * Data em que o documento foi emitido no formato YYYY-MM-DD (cf. RFC 3339, section 5.8)
   **/
  @ApiModelProperty(value = "Data em que o documento foi emitido no formato YYYY-MM-DD (cf. RFC 3339, section 5.8)")
  public Date getDataEmissao() {
    return dataEmissao;
  }
  public void setDataEmissao(Date dataEmissao) {
    this.dataEmissao = dataEmissao;
  }

  /**
   * Data de validade do documento no formato YYYY-MM-DD (cf. RFC 3339, section 5.8)
   **/
  @ApiModelProperty(value = "Data de validade do documento no formato YYYY-MM-DD (cf. RFC 3339, section 5.8)")
  public Date getDataValidade() {
    return dataValidade;
  }
  public void setDataValidade(Date dataValidade) {
    this.dataValidade = dataValidade;
  }

  /**
   * Código de Segurança da Carteira Nacional de Habilitação
   **/
  @ApiModelProperty(value = "Código de Segurança da Carteira Nacional de Habilitação")
  public String getCodigoSegurancaCNH() {
    return codigoSegurancaCNH;
  }
  public void setCodigoSegurancaCNH(String codigoSegurancaCNH) {
    this.codigoSegurancaCNH = codigoSegurancaCNH;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Documento documento = (Documento) o;
    return (this.tipoDocumento == null ? documento.tipoDocumento == null : this.tipoDocumento.equals(documento.tipoDocumento)) &&
        (this.numeroDocumento == null ? documento.numeroDocumento == null : this.numeroDocumento.equals(documento.numeroDocumento)) &&
        (this.orgaoExpedidor == null ? documento.orgaoExpedidor == null : this.orgaoExpedidor.equals(documento.orgaoExpedidor)) &&
        (this.ufEmissao == null ? documento.ufEmissao == null : this.ufEmissao.equals(documento.ufEmissao)) &&
        (this.dataEmissao == null ? documento.dataEmissao == null : this.dataEmissao.equals(documento.dataEmissao)) &&
        (this.dataValidade == null ? documento.dataValidade == null : this.dataValidade.equals(documento.dataValidade)) &&
        (this.codigoSegurancaCNH == null ? documento.codigoSegurancaCNH == null : this.codigoSegurancaCNH.equals(documento.codigoSegurancaCNH));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tipoDocumento == null ? 0: this.tipoDocumento.hashCode());
    result = 31 * result + (this.numeroDocumento == null ? 0: this.numeroDocumento.hashCode());
    result = 31 * result + (this.orgaoExpedidor == null ? 0: this.orgaoExpedidor.hashCode());
    result = 31 * result + (this.ufEmissao == null ? 0: this.ufEmissao.hashCode());
    result = 31 * result + (this.dataEmissao == null ? 0: this.dataEmissao.hashCode());
    result = 31 * result + (this.dataValidade == null ? 0: this.dataValidade.hashCode());
    result = 31 * result + (this.codigoSegurancaCNH == null ? 0: this.codigoSegurancaCNH.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Documento {\n");
    
    sb.append("  tipoDocumento: ").append(tipoDocumento).append("\n");
    sb.append("  numeroDocumento: ").append(numeroDocumento).append("\n");
    sb.append("  orgaoExpedidor: ").append(orgaoExpedidor).append("\n");
    sb.append("  ufEmissao: ").append(ufEmissao).append("\n");
    sb.append("  dataEmissao: ").append(dataEmissao).append("\n");
    sb.append("  dataValidade: ").append(dataValidade).append("\n");
    sb.append("  codigoSegurancaCNH: ").append(codigoSegurancaCNH).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
