/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Definição de endereço
 **/
@ApiModel(description = "Definição de endereço")
public class Endereco {
  
  @SerializedName("cep")
  private String cep = null;
  @SerializedName("logradouro")
  private String logradouro = null;
  @SerializedName("bairro")
  private String bairro = null;
  @SerializedName("uf")
  private String uf = null;
  @SerializedName("cidade")
  private String cidade = null;
  @SerializedName("numero")
  private String numero = null;
  @SerializedName("complemento")
  private String complemento = null;

  /**
   * Código Postal Brasileiro
   **/
  @ApiModelProperty(value = "Código Postal Brasileiro")
  public String getCep() {
    return cep;
  }
  public void setCep(String cep) {
    this.cep = cep;
  }

  /**
   * logradouro do endereço
   **/
  @ApiModelProperty(value = "logradouro do endereço")
  public String getLogradouro() {
    return logradouro;
  }
  public void setLogradouro(String logradouro) {
    this.logradouro = logradouro;
  }

  /**
   * bairro do endereço, preferencialmente lexicográficamente igual a descrição obtida pelo uso do CEP
   **/
  @ApiModelProperty(value = "bairro do endereço, preferencialmente lexicográficamente igual a descrição obtida pelo uso do CEP")
  public String getBairro() {
    return bairro;
  }
  public void setBairro(String bairro) {
    this.bairro = bairro;
  }

  /**
   * Unidade da Federação do endereço
   **/
  @ApiModelProperty(value = "Unidade da Federação do endereço")
  public String getUf() {
    return uf;
  }
  public void setUf(String uf) {
    this.uf = uf;
  }

  /**
   * Município do endereço. Formato é o nome lexicograficamente igual a descrição do IBGE ou o código de cidade completo do IBGE
   **/
  @ApiModelProperty(value = "Município do endereço. Formato é o nome lexicograficamente igual a descrição do IBGE ou o código de cidade completo do IBGE")
  public String getCidade() {
    return cidade;
  }
  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  /**
   * Número do logradouro no endereço
   **/
  @ApiModelProperty(value = "Número do logradouro no endereço")
  public String getNumero() {
    return numero;
  }
  public void setNumero(String numero) {
    this.numero = numero;
  }

  /**
   * Complemento do Endereço
   **/
  @ApiModelProperty(value = "Complemento do Endereço")
  public String getComplemento() {
    return complemento;
  }
  public void setComplemento(String complemento) {
    this.complemento = complemento;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Endereco endereco = (Endereco) o;
    return (this.cep == null ? endereco.cep == null : this.cep.equals(endereco.cep)) &&
        (this.logradouro == null ? endereco.logradouro == null : this.logradouro.equals(endereco.logradouro)) &&
        (this.bairro == null ? endereco.bairro == null : this.bairro.equals(endereco.bairro)) &&
        (this.uf == null ? endereco.uf == null : this.uf.equals(endereco.uf)) &&
        (this.cidade == null ? endereco.cidade == null : this.cidade.equals(endereco.cidade)) &&
        (this.numero == null ? endereco.numero == null : this.numero.equals(endereco.numero)) &&
        (this.complemento == null ? endereco.complemento == null : this.complemento.equals(endereco.complemento));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cep == null ? 0: this.cep.hashCode());
    result = 31 * result + (this.logradouro == null ? 0: this.logradouro.hashCode());
    result = 31 * result + (this.bairro == null ? 0: this.bairro.hashCode());
    result = 31 * result + (this.uf == null ? 0: this.uf.hashCode());
    result = 31 * result + (this.cidade == null ? 0: this.cidade.hashCode());
    result = 31 * result + (this.numero == null ? 0: this.numero.hashCode());
    result = 31 * result + (this.complemento == null ? 0: this.complemento.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Endereco {\n");
    
    sb.append("  cep: ").append(cep).append("\n");
    sb.append("  logradouro: ").append(logradouro).append("\n");
    sb.append("  bairro: ").append(bairro).append("\n");
    sb.append("  uf: ").append(uf).append("\n");
    sb.append("  cidade: ").append(cidade).append("\n");
    sb.append("  numero: ").append(numero).append("\n");
    sb.append("  complemento: ").append(complemento).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
