/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import OramaCadastroAndroid.PerfilUsuario;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListaPerfilUsuario {
  
  @SerializedName("quantidade")
  private BigDecimal quantidade = null;
  @SerializedName("proximo")
  private String proximo = null;
  @SerializedName("anterior")
  private String anterior = null;
  @SerializedName("resultados")
  private List<PerfilUsuario> resultados = null;

  /**
   * quantidade de elementos que foram retornados
   **/
  @ApiModelProperty(value = "quantidade de elementos que foram retornados")
  public BigDecimal getQuantidade() {
    return quantidade;
  }
  public void setQuantidade(BigDecimal quantidade) {
    this.quantidade = quantidade;
  }

  /**
   * URL da próxima página de resultados
   **/
  @ApiModelProperty(value = "URL da próxima página de resultados")
  public String getProximo() {
    return proximo;
  }
  public void setProximo(String proximo) {
    this.proximo = proximo;
  }

  /**
   * URL da próxima anterior de resultados
   **/
  @ApiModelProperty(value = "URL da próxima anterior de resultados")
  public String getAnterior() {
    return anterior;
  }
  public void setAnterior(String anterior) {
    this.anterior = anterior;
  }

  /**
   * Lista composta por objetos do tipo Perfil
   **/
  @ApiModelProperty(value = "Lista composta por objetos do tipo Perfil")
  public List<PerfilUsuario> getResultados() {
    return resultados;
  }
  public void setResultados(List<PerfilUsuario> resultados) {
    this.resultados = resultados;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListaPerfilUsuario listaPerfilUsuario = (ListaPerfilUsuario) o;
    return (this.quantidade == null ? listaPerfilUsuario.quantidade == null : this.quantidade.equals(listaPerfilUsuario.quantidade)) &&
        (this.proximo == null ? listaPerfilUsuario.proximo == null : this.proximo.equals(listaPerfilUsuario.proximo)) &&
        (this.anterior == null ? listaPerfilUsuario.anterior == null : this.anterior.equals(listaPerfilUsuario.anterior)) &&
        (this.resultados == null ? listaPerfilUsuario.resultados == null : this.resultados.equals(listaPerfilUsuario.resultados));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.quantidade == null ? 0: this.quantidade.hashCode());
    result = 31 * result + (this.proximo == null ? 0: this.proximo.hashCode());
    result = 31 * result + (this.anterior == null ? 0: this.anterior.hashCode());
    result = 31 * result + (this.resultados == null ? 0: this.resultados.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListaPerfilUsuario {\n");
    
    sb.append("  quantidade: ").append(quantidade).append("\n");
    sb.append("  proximo: ").append(proximo).append("\n");
    sb.append("  anterior: ").append(anterior).append("\n");
    sb.append("  resultados: ").append(resultados).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
