/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import OramaCadastroAndroid.LoginObjeto;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginCriado {
  
  @SerializedName("login")
  private LoginObjeto login = null;
  @SerializedName("token")
  private String token = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public LoginObjeto getLogin() {
    return login;
  }
  public void setLogin(LoginObjeto login) {
    this.login = login;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginCriado loginCriado = (LoginCriado) o;
    return (this.login == null ? loginCriado.login == null : this.login.equals(loginCriado.login)) &&
        (this.token == null ? loginCriado.token == null : this.token.equals(loginCriado.token));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.login == null ? 0: this.login.hashCode());
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginCriado {\n");
    
    sb.append("  login: ").append(login).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
