/**
 * Criação de Contas
 * API de Criação de Contas.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cadastro_api@orama.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package OramaCadastroAndroid;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginSenhaObjeto {
  
  @SerializedName("nome")
  private String nome = null;
  @SerializedName("celular")
  private String celular = null;
  @SerializedName("cpf")
  private String cpf = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("senha")
  private String senha = null;

  /**
   * Campo texto de preenchimento obrigatório para o preenchimento do nome completo do cliente.
   **/
  @ApiModelProperty(required = true, value = "Campo texto de preenchimento obrigatório para o preenchimento do nome completo do cliente.")
  public String getNome() {
    return nome;
  }
  public void setNome(String nome) {
    this.nome = nome;
  }

  /**
   * Telefone celular contendo o código de país e de cidade. Enviar somente os dígitos.
   **/
  @ApiModelProperty(required = true, value = "Telefone celular contendo o código de país e de cidade. Enviar somente os dígitos.")
  public String getCelular() {
    return celular;
  }
  public void setCelular(String celular) {
    this.celular = celular;
  }

  /**
   * CPF deve ser válido e não ter sido usado anteriormente. Enviar somente os dígitos.
   **/
  @ApiModelProperty(required = true, value = "CPF deve ser válido e não ter sido usado anteriormente. Enviar somente os dígitos.")
  public String getCpf() {
    return cpf;
  }
  public void setCpf(String cpf) {
    this.cpf = cpf;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Senha de seis dígitos.
   **/
  @ApiModelProperty(required = true, value = "Senha de seis dígitos.")
  public String getSenha() {
    return senha;
  }
  public void setSenha(String senha) {
    this.senha = senha;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginSenhaObjeto loginSenhaObjeto = (LoginSenhaObjeto) o;
    return (this.nome == null ? loginSenhaObjeto.nome == null : this.nome.equals(loginSenhaObjeto.nome)) &&
        (this.celular == null ? loginSenhaObjeto.celular == null : this.celular.equals(loginSenhaObjeto.celular)) &&
        (this.cpf == null ? loginSenhaObjeto.cpf == null : this.cpf.equals(loginSenhaObjeto.cpf)) &&
        (this.email == null ? loginSenhaObjeto.email == null : this.email.equals(loginSenhaObjeto.email)) &&
        (this.senha == null ? loginSenhaObjeto.senha == null : this.senha.equals(loginSenhaObjeto.senha));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.nome == null ? 0: this.nome.hashCode());
    result = 31 * result + (this.celular == null ? 0: this.celular.hashCode());
    result = 31 * result + (this.cpf == null ? 0: this.cpf.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.senha == null ? 0: this.senha.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginSenhaObjeto {\n");
    
    sb.append("  nome: ").append(nome).append("\n");
    sb.append("  celular: ").append(celular).append("\n");
    sb.append("  cpf: ").append(cpf).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  senha: ").append(senha).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
